### ISSUE TITLE
SSLError

### ISSUE THREAD

**Issue by krychu** [mopemope/meinheld#27]
Hi,

I've been using meinheld as a backend with chaussette to run my webapp. I've run into a problem that while trying to make a post request with the requests library I get the following exception:

SSLError: [Errno 2] _ssl.c:504: The operation did not complete (read)

But when I change the backend to waitress (for example) the problem is gone. So I thought it had something to do with meinheld.

Thanks

**Comment by eoghanmurray** [comment]
Getting this too. I see that there used to be 'patch_ssl' but it was removed in https://github.com/mopemope/meinheld/commit/68e5854bbc43e0010b56c80248e15a97336dfe6d
Disabling 'patch_socket' causes the code to work (`smtp.starttls()` triggers the error), but I've no idea whether this has performance effects or otherwise so will likely be switching to waitress unless there is a fix?

**Comment by methane** [comment]
I don't recommend monkeypatching (msocket) unless you know what you do.
meinheld works very fine like other preforking servers (but more faster) without monkeypatching.
